// Domande di storia del calcio e del tennis per StatsFight a quiz (09/10, richiesta utente). Ogni domanda:
// { q: testo, opts: risposte (la prima e' quella giusta: l'app le mescola), y: anno a cui si riferisce }.
// Solo fatti certi e verificabili; per aggiungerne basta una riga. Le domande di attualita' invece le calcola il
// server coi dati veri (signals/quiz_attualita.py: classifiche e risultati recenti).
window.QUIZ_STORIA = {
  calcio: [
    { q: "Chi ha vinto i Mondiali del 2006 in Germania?", opts: ["Italia", "Francia", "Germania", "Brasile"] },
    { q: "Chi segnò il rigore decisivo nella finale dei Mondiali 2006?", opts: ["Fabio Grosso", "Alessandro Del Piero", "Andrea Pirlo", "Francesco Totti"] },
    { q: "In quale stadio si giocò la finale dei Mondiali 2006?", opts: ["Olympiastadion di Berlino", "Allianz Arena di Monaco", "Westfalenstadion di Dortmund", "Stade de France"] },
    { q: "Chi era il CT dell'Italia campione del mondo nel 2006?", opts: ["Marcello Lippi", "Giovanni Trapattoni", "Arrigo Sacchi", "Cesare Prandelli"] },
    { q: "Chi ha vinto i Mondiali del 2022 in Qatar?", opts: ["Argentina", "Francia", "Croazia", "Marocco"] },
    { q: "Chi ha vinto i Mondiali del 2018 in Russia?", opts: ["Francia", "Croazia", "Belgio", "Inghilterra"] },
    { q: "Chi ha vinto i Mondiali del 2014 in Brasile?", opts: ["Germania", "Argentina", "Paesi Bassi", "Brasile"] },
    { q: "Chi ha vinto i Mondiali del 2010 in Sudafrica?", opts: ["Spagna", "Paesi Bassi", "Germania", "Uruguay"] },
    { q: "Chi ha vinto i Mondiali del 1982 in Spagna?", opts: ["Italia", "Germania Ovest", "Brasile", "Polonia"] },
    { q: "Chi era il CT dell'Italia campione del mondo nel 1982?", opts: ["Enzo Bearzot", "Azeglio Vicini", "Ferruccio Valcareggi", "Dino Zoff"] },
    { q: "Chi fu il capocannoniere dei Mondiali 1990 in Italia?", opts: ["Totò Schillaci", "Roberto Baggio", "Gary Lineker", "Diego Maradona"] },
    { q: "Chi vinse i Mondiali del 1990, giocati in Italia?", opts: ["Germania Ovest", "Argentina", "Italia", "Inghilterra"] },
    { q: "La 'mano de Dios' di Maradona ai Mondiali 1986 fu contro quale nazionale?", opts: ["Inghilterra", "Belgio", "Germania Ovest", "Italia"] },
    { q: "Quanti Mondiali ha vinto l'Italia?", opts: ["4", "3", "5", "2"] },
    { q: "Quanti Mondiali ha vinto il Brasile?", opts: ["5", "4", "6", "3"] },
    { q: "Chi ha vinto gli Europei giocati nel 2021 (Euro 2020)?", opts: ["Italia", "Inghilterra", "Spagna", "Danimarca"] },
    { q: "Chi era il CT dell'Italia campione d'Europa a Wembley nel 2021?", opts: ["Roberto Mancini", "Antonio Conte", "Luciano Spalletti", "Gian Piero Ventura"] },
    { q: "Chi ha vinto gli Europei del 2024 in Germania?", opts: ["Spagna", "Inghilterra", "Francia", "Paesi Bassi"] },
    { q: "Chi ha vinto gli Europei del 2016 in Francia?", opts: ["Portogallo", "Francia", "Germania", "Galles"] },
    { q: "In che anno l'Italia vinse il suo primo Europeo?", opts: ["1968", "1982", "2000", "1964"] },
    { q: "Chi ha vinto la Champions League 2023, battendo l'Inter in finale a Istanbul?", opts: ["Manchester City", "Real Madrid", "Bayern Monaco", "Chelsea"] },
    { q: "Contro chi l'Inter vinse la Champions League del 2010?", opts: ["Bayern Monaco", "Barcellona", "Manchester United", "Chelsea"] },
    { q: "Chi allenava l'Inter del triplete nel 2010?", opts: ["José Mourinho", "Roberto Mancini", "Claudio Ranieri", "Rafael Benítez"] },
    { q: "Chi vinse la finale di Champions 2003 fra Milan e Juventus?", opts: ["Milan, ai rigori", "Juventus, ai rigori", "Milan, 2-1", "Juventus, 1-0"] },
    { q: "Nella finale di Champions 2005 a Istanbul il Liverpool rimontò da 0-3 contro…", opts: ["Milan", "Juventus", "Barcellona", "Chelsea"] },
    { q: "Chi vinse la Champions League del 2007, ad Atene?", opts: ["Milan", "Liverpool", "Barcellona", "Manchester United"] },
    { q: "Quante Coppe dei Campioni / Champions League ha vinto il Milan?", opts: ["7", "5", "6", "8"] },
    { q: "Quale squadra ha vinto più Coppe dei Campioni / Champions League?", opts: ["Real Madrid", "Milan", "Bayern Monaco", "Liverpool"] },
    { q: "Quante Coppe dei Campioni vinse di fila il Real Madrid dal 1956?", opts: ["5", "3", "4", "6"] },
    { q: "Prima squadra italiana a vincere la Coppa dei Campioni, nel 1963?", opts: ["Milan", "Inter", "Juventus", "Torino"] },
    { q: "Chi ha vinto la Champions League 2024, a Wembley?", opts: ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Monaco"] },
    { q: "Chi ha vinto la Champions League 2025, battendo l'Inter 5-0 in finale?", opts: ["Paris Saint-Germain", "Barcellona", "Arsenal", "Real Madrid"] },
    { q: "Chi ha vinto la Champions League 2021?", opts: ["Chelsea", "Manchester City", "Bayern Monaco", "Real Madrid"] },
    { q: "Chi allenava il Barcellona del triplete del 2009?", opts: ["Pep Guardiola", "Frank Rijkaard", "Luis Enrique", "Johan Cruijff"] },
    { q: "Quale squadra italiana ha vinto l'Europa League 2024?", opts: ["Atalanta", "Roma", "Inter", "Fiorentina"] },
    { q: "Contro chi l'Atalanta vinse 3-0 la finale di Europa League 2024?", opts: ["Bayer Leverkusen", "Siviglia", "Liverpool", "Marsiglia"] },
    { q: "Quale squadra italiana vinse la prima Conference League, nel 2022?", opts: ["Roma", "Fiorentina", "Lazio", "Atalanta"] },
    { q: "Chi ha vinto lo scudetto 2022-23?", opts: ["Napoli", "Lazio", "Inter", "Milan"] },
    { q: "Chi ha vinto lo scudetto 2023-24, quello della seconda stella?", opts: ["Inter", "Milan", "Juventus", "Napoli"] },
    { q: "Chi ha vinto lo scudetto 2024-25?", opts: ["Napoli", "Inter", "Atalanta", "Juventus"] },
    { q: "Chi allenava il Leicester campione d'Inghilterra nel 2016?", opts: ["Claudio Ranieri", "Carlo Ancelotti", "Roberto Mancini", "Antonio Conte"] },
    { q: "Chi vinse il Pallone d'oro nel 2006?", opts: ["Fabio Cannavaro", "Gianluigi Buffon", "Thierry Henry", "Ronaldinho"] },
    { q: "Chi vinse il Pallone d'oro nel 2007?", opts: ["Kaká", "Cristiano Ronaldo", "Lionel Messi", "Andrea Pirlo"] },
    { q: "Quanti Palloni d'oro ha vinto Lionel Messi?", opts: ["8", "7", "6", "5"] },
    { q: "Chi ha vinto il Pallone d'oro 2024?", opts: ["Rodri", "Vinícius Júnior", "Jude Bellingham", "Kylian Mbappé"] },
    { q: "Chi ha vinto il Pallone d'oro 2025?", opts: ["Ousmane Dembélé", "Lamine Yamal", "Kylian Mbappé", "Mohamed Salah"] },
    { q: "Chi è il miglior marcatore di sempre della Serie A?", opts: ["Silvio Piola", "Francesco Totti", "Gunnar Nordahl", "Giuseppe Meazza"] },
    { q: "Chi è il miglior marcatore di sempre della Nazionale italiana?", opts: ["Gigi Riva", "Giuseppe Meazza", "Roberto Baggio", "Alessandro Del Piero"] },
    { q: "Chi ha il record di presenze in Serie A?", opts: ["Gianluigi Buffon", "Paolo Maldini", "Francesco Totti", "Javier Zanetti"] },
    { q: "In che anno Cristiano Ronaldo arrivò alla Juventus?", opts: ["2018", "2016", "2019", "2020"] }
  ],
  tennis: [
    { q: "Chi ha vinto più tornei dello Slam fra gli uomini?", opts: ["Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"] },
    { q: "Quanti Roland Garros ha vinto Rafael Nadal?", opts: ["14", "12", "13", "11"] },
    { q: "Quanti Wimbledon ha vinto Roger Federer?", opts: ["8", "7", "6", "9"] },
    { q: "Chi è stato il primo italiano a vincere l'Australian Open?", opts: ["Jannik Sinner", "Matteo Berrettini", "Fabio Fognini", "Adriano Panatta"] },
    { q: "Contro chi Sinner vinse la finale dell'Australian Open 2024, rimontando da due set sotto?", opts: ["Daniil Medvedev", "Novak Djokovic", "Alexander Zverev", "Stefanos Tsitsipas"] },
    { q: "Chi ha vinto l'Australian Open 2025 fra gli uomini?", opts: ["Jannik Sinner", "Alexander Zverev", "Carlos Alcaraz", "Novak Djokovic"] },
    { q: "Chi ha vinto lo US Open 2024 fra gli uomini?", opts: ["Jannik Sinner", "Taylor Fritz", "Carlos Alcaraz", "Daniil Medvedev"] },
    { q: "Chi ha vinto Wimbledon 2025 fra gli uomini?", opts: ["Jannik Sinner", "Carlos Alcaraz", "Novak Djokovic", "Taylor Fritz"] },
    { q: "Chi ha vinto il Roland Garros 2025, salvando tre match point in finale contro Sinner?", opts: ["Carlos Alcaraz", "Novak Djokovic", "Alexander Zverev", "Casper Ruud"] },
    { q: "Chi ha vinto lo US Open 2025 fra gli uomini?", opts: ["Carlos Alcaraz", "Jannik Sinner", "Novak Djokovic", "Taylor Fritz"] },
    { q: "Chi ha vinto Wimbledon 2024 fra gli uomini?", opts: ["Carlos Alcaraz", "Novak Djokovic", "Jannik Sinner", "Daniil Medvedev"] },
    { q: "Chi è stato il primo italiano numero 1 del ranking ATP?", opts: ["Jannik Sinner", "Adriano Panatta", "Matteo Berrettini", "Corrado Barazzutti"] },
    { q: "Chi ha vinto le ATP Finals 2024 a Torino?", opts: ["Jannik Sinner", "Taylor Fritz", "Carlos Alcaraz", "Alexander Zverev"] },
    { q: "In quale città si giocano le ATP Finals dal 2021?", opts: ["Torino", "Londra", "Milano", "Shanghai"] },
    { q: "In che anno Adriano Panatta vinse il Roland Garros?", opts: ["1976", "1973", "1979", "1982"] },
    { q: "Prima del 2023, in che anno l'Italia aveva vinto la Coppa Davis?", opts: ["1976", "1980", "1998", "1960"] },
    { q: "In che anno Francesca Schiavone vinse il Roland Garros?", opts: ["2010", "2011", "2008", "2012"] },
    { q: "Chi vinse lo US Open 2015, in una finale tutta italiana?", opts: ["Flavia Pennetta", "Roberta Vinci", "Sara Errani", "Francesca Schiavone"] },
    { q: "Contro chi Matteo Berrettini giocò la finale di Wimbledon 2021?", opts: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Daniil Medvedev"] },
    { q: "Chi battè Jasmine Paolini nella finale del Roland Garros 2024?", opts: ["Iga Swiatek", "Coco Gauff", "Aryna Sabalenka", "Elena Rybakina"] },
    { q: "Paolini ed Errani a Parigi 2024 hanno vinto l'oro olimpico in…", opts: ["doppio femminile", "doppio misto", "singolare", "squadre"] },
    { q: "Chi ha vinto l'oro olimpico nel singolare maschile a Parigi 2024?", opts: ["Novak Djokovic", "Carlos Alcaraz", "Lorenzo Musetti", "Jannik Sinner"] },
    { q: "Quanti tornei dello Slam ha vinto Serena Williams?", opts: ["23", "22", "24", "21"] },
    { q: "Chi ha il record di Slam vinti nel tennis femminile?", opts: ["Margaret Court", "Serena Williams", "Steffi Graf", "Martina Navratilova"] },
    { q: "Chi vinse il 'Golden Slam' (i quattro Slam e l'oro olimpico) nel 1988?", opts: ["Steffi Graf", "Martina Navratilova", "Chris Evert", "Monica Seles"] },
    { q: "Quale torneo dello Slam si gioca sull'erba?", opts: ["Wimbledon", "Roland Garros", "US Open", "Australian Open"] },
    { q: "Su che superficie si gioca il Roland Garros?", opts: ["Terra rossa", "Erba", "Cemento", "Sintetico al coperto"] },
    { q: "Dove si giocano gli Internazionali d'Italia?", opts: ["Foro Italico, Roma", "Milano", "Torino", "Firenze"] },
    { q: "Quanti Wimbledon di fila vinse Björn Borg dal 1976?", opts: ["5", "4", "3", "6"] },
    { q: "Chi giocò contro John Isner la partita più lunga della storia, a Wimbledon 2010?", opts: ["Nicolas Mahut", "Andy Roddick", "Rafael Nadal", "Gael Monfils"] },
    { q: "Chi NON fa parte dei 'Big Three' del tennis?", opts: ["Andy Murray", "Roger Federer", "Rafael Nadal", "Novak Djokovic"] },
    { q: "In quale torneo Roger Federer giocò la sua ultima partita, nel 2022?", opts: ["Laver Cup", "Wimbledon", "Swiss Indoors Basilea", "ATP Finals"] },
    { q: "Dove ha chiuso la carriera Rafael Nadal, nel 2024?", opts: ["Coppa Davis a Malaga", "Roland Garros", "Olimpiadi di Parigi", "Madrid"] },
    { q: "Nel tie-break si vince con…", opts: ["7 punti e almeno 2 di scarto", "6 punti", "10 punti", "7 punti anche con 1 di scarto"] },
    { q: "Chi battè Jasmine Paolini nella finale di Wimbledon 2024?", opts: ["Barbora Krejcikova", "Elena Rybakina", "Iga Swiatek", "Ons Jabeur"] }
  ]
};
